### ISSUE TITLE
Carriage return '\r' persisting during file read.

### ISSUE THREAD

**Issue by mon369** [simon-inoc/Open-Source#1]
Line 43-44 in [app.js](app.js): Parsing the [numbers.txt](numbers.txt) file produces an array of strings splitted with the '\n' delimeter, however also retains a carriage return '\r' in the output as follows.  This bug needs to be fixed in order to sanitize the original data from unintended characters.

```
[ 'hello from the other side\r',
  'hello\r',
  'can you\r',
  'hear me\r',
  '4161234567\r',
  '1112223333\r',
  '4164915050\r',
  '9052721441\r',
  '6479237466\r',
  '0011aaaaaa' ]
```

**Comment by irrationalRock** [comment]
i'll take a look at this issue
